### ISSUE TITLE
Run benchmarks and tests on Zuse cluster.

### ISSUE THREAD

**Issue by PixR2** [flxw/cluster-computing-up#1]
@flxw running the benchmarks and tests on the Use cluster requires the following steps:
1. Run `benchmark.sh <path to executable> 1000000000 16 benchmark_results.txt`
2. Extra to test consistency: Run `test_consistency.sh <path to executable> <number of samples> 8 100 consistency_results.txt`
-- Maybe run this with num. samples: 10k, 100k, 1m, 10m, 100m, 1bilion (Use the same output file each time.)
3. Copy _benchmark_results.txt_ and _consistency_results.txt_ and paste them here in a comment so I can generate some nice diagrams.

**Comment by flxw** [comment]
Prego. Einmal für CPU-affin und einmal für nicht-CPU-affin 👍 
[benchmark_results_affine_montecarlo_pi.txt](https://github.com/flxw/cluster-computing-up/files/1039792/benchmark_results_affine_montecarlo_pi.txt)
[benchmark_results_montecarlo_pi.txt](https://github.com/flxw/cluster-computing-up/files/1039789/benchmark_results_montecarlo_pi.txt)
[consistency_results_affine_montecarlo_pi.txt](https://github.com/flxw/cluster-computing-up/files/1039791/consistency_results_affine_montecarlo_pi.txt)
[consistency_results_montecarlo_pi.txt](https://github.com/flxw/cluster-computing-up/files/1039790/consistency_results_montecarlo_pi.txt)
